***1 Machine Learning Lab#3***

In [2]:
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB

In [3]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']


In [4]:
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)

print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [5]:
temp_encoded = le.fit_transform(temp)

print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [6]:
label = le.fit_transform(play)
print(label)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [7]:
features = tuple(zip(weather_encoded,temp_encoded))
print(features)

((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [8]:
model = CategoricalNB()
model.fit(features,label)


CategoricalNB()

In [9]:
prediction = model.predict([[0,2]])
print(prediction)

[1]


In [10]:
prediction = model.predict([[0,1]])
print(prediction)

[1]


In [11]:
prediction = model.predict([[2,2]])
print(prediction)

[0]


In [12]:
model = MultinomialNB()

model.fit(features,label)

MultinomialNB()

In [13]:
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


In [14]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [15]:
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

In [16]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=4)

In [17]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [18]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9333333333333333


In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[15,  2],
       [ 0, 13]])

In [20]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 1.0
recall: 0.8823529411764706
