In [14]:
import numpy as np
import torch

In [15]:
import torch.nn as nn

In [16]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64],
                   [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')

In [17]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [18]:
from torch.utils.data import TensorDataset, DataLoader

**LAB-4**

In [19]:
import numpy as np
import torch

In [20]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [21]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [22]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [23]:
weights = np.array([[0.5,1,1.5]],dtype='float32')
weights = torch.from_numpy(weights)
weights = torch.t(weights)
print(weights)

tensor([[0.5000],
        [1.0000],
        [1.5000]])


In [24]:
multiplied = torch.mm(inputs,weights)

In [25]:
bias = torch.tensor([[-2.2671,-2.2671,-2.2671,-2.2671,-2.2671]])
bias = torch.t(bias)
print(bias)

tensor([[-2.2671],
        [-2.2671],
        [-2.2671],
        [-2.2671],
        [-2.2671]])


In [26]:
prediction = torch.add(multiplied,bias)
print(prediction)

tensor([[165.7329],
        [227.2329],
        [262.2329],
        [147.2329],
        [233.2329]])


In [28]:
sum = 0
for i in range(0,5):
  sum = sum + ((prediction[i]-targets[i])**2)
loss = sum/10
print(loss)

tensor([8658.4922])


In [31]:
print(weights.grad)

None
